# Generated by Django 5.1 on 2024-08-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.CharField(max_length=255)),
                ('produto_nome', models.CharField(max_length=255)),
                ('produto_imagem', models.URLField()),
                ('produto_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_review', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='clientes.cliente')),
            ],
        ),
    ]
